### ISSUE TITLE
newline support

### ISSUE THREAD

**Issue by Command-Master** [McTsts/Minecraft-String-Utilities#1]
is it possible to add newline (\n) to the charset?

**Comment by McTsts** [comment]
`"\n"` simply becomes `["\\","n"]`, the newline character itself shows up as `` if written in the game, so I don't think anything more is possible.
When parsing a book what is shown above would show up in a book.
I believe @gibbsly was actually adjusting his JSON parser (which you would presumably use to parse a book) to do something special for `["\\","n"]` however.

**Comment by Command-Master** [comment]
thanks for the response!
I tried to copy multiple lines from a book, and they're shown properly in-game
![image](https://user-images.githubusercontent.com/55664973/71392893-89b79c80-2612-11ea-981c-7c104d8a1d09.png)

**Comment by McTsts** [comment]
Yes, and that is parsed into \\n because the new line character shows up as a private use character if put into Minecraft in another way than \n - at least as far as I know

**Comment by Command-Master** [comment]
maybe it's possible to make it replace it with another character if it detects a newline (if something is below space)?

**Comment by Command-Master** [comment]
or it's maybe possible to copy it from a static book to the storage because I managed to put a newline in the display.Name of an item
![2019-12-24_07 02 55](https://user-images.githubusercontent.com/55664973/71394736-8543b180-261b-11ea-8943-bfd45c1c7800.png)

**Comment by gibbsly** [comment]
the issue is we can't particularly detect a character we can't type into a function, the _newline_ character is how minecraft detects the start of a new command in a function file. The best way we found to actually be able to detect a new line is to put the text from the book onto a sign, then copying the sign's json text into the input. If you do that the char array will have ["\\\\","n"] in it.

**Comment by Command-Master** [comment]
ok, thanks. also what about
;
^
`
@
I need them for a project. can I add them somehow?

**Comment by Command-Master** [comment]
> The best way we found to actually be able to detect a new line is to put the text from the book onto a sign, then copying the sign's json text into the input. If you do that the char array will have ["\","n"] in it.

I doesn't work ):... It says 

> An unexpected error occurred trying to execute that command

**Comment by gibbsly** [comment]
`/data modify block 8 1 -10 Text1 set value '{"nbt":"SelectedItem.tag.pages[0]","entity":"@p"}'` will put the text of a book into a sign's first line, ts will probably have to update the module to add extra chars

**Comment by Command-Master** [comment]
oh thanks, I did
> data modify block 8 1 -10 Text1 set from entity @p SelectedItem.tag.pages[0]

**Comment by McTsts** [comment]
The new line is `["\\","n"]` (double backslash) not `["\","n"]` after parsing. [This function](https://github.com/McTsts/Minecraft-String-Utilities/blob/master/examples/data/example/functions/15_from_book.mcfunction) is an example of parsing a book. If you want me to, I can the characters you need for this version?
Otherwise, you can add the characters to [this function](https://github.com/McTsts/Minecraft-String-Utilities/blob/master/strings/data/string/functions/run/id_to_char.mcfunction), and adjust the value of total [here](https://github.com/McTsts/Minecraft-String-Utilities/blob/master/strings/data/string/functions/load.mcfunction). If you want me to simply add your characters to this version just let me know!
